### ISSUE TITLE
NPE in Driver.connect() method

### ISSUE THREAD

**Issue by bedrin** [sniffy/sniffy#194]
```
Caused by: java.lang.NullPointerException: null
	at io.sniffy.util.StackTraceExtractor.getTraceForProxiedMethod(StackTraceExtractor.java:15) ~[jdbcSniffer.jar:na]
	at io.sniffy.Sniffy.exitJdbcMethod(Sniffy.java:126) ~[jdbcSniffer.jar:na]
	at io.sniffy.sql.SniffyDriver.connect(SniffyDriver.java:84) ~[jdbcSniffer.jar:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278) ~[tomcat-jdbc.jar:na]
	... 48 common frames omitted
```

**Comment by bedrin** [comment]
Fixed in 3.1
