### ISSUE TITLE
ClassNotFoundException when using @EnableSniffy with params and without adapter

### ISSUE THREAD

**Issue by viosng** [sniffy/sniffy#264]
ClassNotFoundException when using @EnableSniffy with params:
@EnableSniffy(monitorJdbc = "${sniffy.enabled}", monitorSocket = "${sniffy.enabled}",
        injectHtml = "${sniffy.enabled}", filterEnabled = "${sniffy.enabled}")
and without the driver adapter:
db.connection.class = oracle.jdbc.OracleDriver
db.connection.url = jdbc:oracle:thin:@//...

Stack trace:
java.lang.ClassNotFoundException: com.sun.proxy.$Proxy116
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.sniffy.util.StackTraceExtractor.getTraceForProxiedMethod(StackTraceExtractor.java:23)
	at io.sniffy.Sniffy.exitJdbcMethod(Sniffy.java:145)
	at io.sniffy.sql.SniffyDataSource.getConnection(SniffyDataSource.java:85)
       ...

**Comment by bedrin** [comment]
Fixed in 3.1.0
