### ISSUE TITLE
java.lang.IllegalArgumentException: null  from SniffySocketChannelAdapter.write(SniffySocketChannelAdapter.java:119)

### ISSUE THREAD

**Issue by bedrin** [sniffy/sniffy#498]
```
java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_291]
	at sun.nio.ch.IOUtil.write(IOUtil.java:68) ~[na:1.8.0_291]

	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470) ~[na:1.8.0_291]

	at io.sniffy.nio.SniffySocketChannelAdapter.write(SniffySocketChannelAdapter.java:119) ~[sniffy-module-nio-3.1.12.jar:na]

	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:135) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1363) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:766) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:719) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:709) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.coyote.http11.filters.VoidOutputFilter.flush(VoidOutputFilter.java:67) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.coyote.http11.filters.IdentityOutputFilter.flush(IdentityOutputFilter.java:117) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1205) [tomcat-embed-core-9.0.53.jar:9.0.53]


	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.coyote.Response.action(Response.java:209) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118) ~[tomcat-embed-core-9.0.53.jar:9.0.53]

	at io.sniffy.servlet.BufferedServletOutputStream.flushImpl(BufferedServletOutputStream.java:59) ~[sniffy-web-3.1.12.jar:na]

	at io.sniffy.servlet.BufferedServletOutputStream.flushIfOpen(BufferedServletOutputStream.java:36) ~[sniffy-web-3.1.12.jar:na]

	at io.sniffy.servlet.BufferedServletResponseWrapper.flushIfPossible(BufferedServletResponseWrapper.java:90) ~[sniffy-web-3.1.12.jar:na]

	at io.sniffy.servlet.SniffyRequestProcessor.processImpl(SniffyRequestProcessor.java:199) [sniffy-web-3.1.12.jar:na]

	at io.sniffy.servlet.SniffyRequestProcessor.process(SniffyRequestProcessor.java:157) [sniffy-web-3.1.12.jar:na]

	at io.sniffy.servlet.SniffyFilter.doFilter(SniffyFilter.java:244) [sniffy-web-3.1.12.jar:na]

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.53.jar:9.0.53]


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.53.jar:9.0.53]
```

**Comment by bedrin** [comment]
Potentially not a Sniffy issue. See https://bz.apache.org/bugzilla/show_bug.cgi?id=60409 for an example

**Comment by bedrin** [comment]
Actually it seems that this issue can only by triggered if ByteBuffer to be written is manipulated concurrently from the wrong therad
