### ISSUE TITLE
ConcurrentModificationException while getting captured network traffic

### ISSUE THREAD

**Issue by bedrin** [sniffy/sniffy#538]
```
2022-06-18T14:25:17.1073687Z java.util.ConcurrentModificationException
2022-06-18T14:25:17.1077870Z 	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
2022-06-18T14:25:17.1080945Z 	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
2022-06-18T14:25:17.1083423Z 	at io.sniffy.Spy.filterTraffic(Spy.java:176)
2022-06-18T14:25:17.1086115Z 	at io.sniffy.Spy.getNetworkTraffic(Spy.java:155)
2022-06-18T14:25:17.1182937Z 	at io.sniffy.tls.CaptureJBossRemotingCaptureTrafficTest.testChannelOptions(CaptureJBossRemotingCaptureTrafficTest.java:186)
2022-06-18T14:25:17.1183611Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-06-18T14:25:17.1184068Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-06-18T14:25:17.1184572Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-18T14:25:17.1184999Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2022-06-18T14:25:17.1185405Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-06-18T14:25:17.1185888Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-06-18T14:25:17.1186404Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-06-18T14:25:17.1186912Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-06-18T14:25:17.1187405Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-06-18T14:25:17.1188106Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-06-18T14:25:17.1188528Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-06-18T14:25:17.1188912Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-06-18T14:25:17.1189349Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2022-06-18T14:25:17.1189781Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2022-06-18T14:25:17.1190234Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2022-06-18T14:25:17.1190725Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2022-06-18T14:25:17.1191141Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2022-06-18T14:25:17.1191518Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2022-06-18T14:25:17.1192020Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2022-06-18T14:25:17.1192430Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2022-06-18T14:25:17.1192822Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2022-06-18T14:25:17.1193263Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-06-18T14:25:17.1193746Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-06-18T14:25:17.1194179Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-06-18T14:25:17.1194556Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2022-06-18T14:25:17.1195159Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
2022-06-18T14:25:17.1195693Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
2022-06-18T14:25:17.1196221Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
2022-06-18T14:25:17.1196734Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
2022-06-18T14:25:17.1197255Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2022-06-18T14:25:17.1197886Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2022-06-18T14:25:17.1198348Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2022-06-18T14:25:17.1198800Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

```

**Comment by bedrin** [comment]
Fixed in https://github.com/sniffy/sniffy/pull/537
