### ISSUE TITLE
CancelledKeyException with XNIO traffic capture

### ISSUE THREAD

**Issue by bedrin** [sniffy/sniffy#539]
```
java.nio.channels.CancelledKeyException
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
	at java.base/sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:96)
	at io.sniffy.nio.SniffySelectionKey.interestOps(SniffySelectionKey.java:80)
	at java.base/java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:217)
	at java.base/java.nio.channels.SelectableChannel.register(SelectableChannel.java:260)
	at org.xnio.nio.SelectorUtils.await(SelectorUtils.java:47)
	at org.xnio.nio.NioSocketConduit.awaitReadable(NioSocketConduit.java:358)
	at org.xnio.conduits.ConduitStreamSourceChannel.awaitReadable(ConduitStreamSourceChannel.java:151)
	at org.xnio.channels.AssembledStreamChannel.awaitReadable(AssembledStreamChannel.java:105)
	at org.xnio.channels.Channels.readBlocking(Channels.java:345)
	at io.sniffy.tls.DecryptLocalhostHttpsTrafficXNIOTest.testLocalhostHttpsTraffic(DecryptLocalhostHttpsTrafficXNIOTest.java:102)
```

**Comment by bedrin** [comment]
Fixed in https://github.com/sniffy/sniffy/issues/540
Also see https://github.com/sniffy/sniffy/issues/545
